server {
    listen 127.0.0.1:8080;
   server_name example.com;
    location /old {
        return 301 /leen;
    }
    location /google {
        return 302 http://www.google.com;
    }

    location /error {
        return 500;
    }

    location / {
      root /Users/macbook/Desktop/megedwebserv/www;
        index index.html;
        methods GET;
    }
}